name: Build iOS .ipa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and export ipa for iOS 15.0
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Build and Archive for iOS 15.0
        env:
          SCHEME: ReDyne
          PROJECT: ReDyne/ReDyne.xcodeproj
          WORKSPACE: ReDyne/ReDyne.xcodeproj/project.xcworkspace
        run: |
          # Clean then archive for ios 15.0
          set -o pipefail
          xcodebuild clean archive \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath "$RUNNER_TEMP/build/ReDyne.xcarchive" \
            IPHONEOS_DEPLOYMENT_TARGET=15.0 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO | xcpretty

          # Manual .ipa packaging for unsigned build
          cd $RUNNER_TEMP/build
          mkdir -p Payload
          cp -R ReDyne.xcarchive/Products/Applications/ReDyne.app Payload/
          zip -r ReDyne.ipa Payload

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReDyne.ipa
          path: ${{ runner.temp }}/build/ReDyne.ipa
